### ISSUE TITLE
Launcher: Mixed Content

### ISSUE THREAD

**Issue by fniephaus** [bertfreudenberg/SqueakJS#46]
When visiting [http**s**://bertfreudenberg.github.io/SqueakJS/run/](https://bertfreudenberg.github.io/SqueakJS/run/), the browser refuses to load images via ```http://```.

> Mixed Content: The page at 'https://bertfreudenberg.github.io/SqueakJS/run/#url=http://freudenbergs.de/…kjs&files=[Squeak4.5-13680.image,Squeak4.5-13680.changes,SqueakV41.sources]' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://freudenbergs.de/bert/squeakjs/Squeak4.5-13680.image'. This request has been blocked; the content must be served over HTTPS.

Providing images through ```https://``` will solve the problem.

**Comment by krono** [comment]
Is  bertfreudenberg.github.io HSTS? If not, I think, this may wait until after the launch of letsencrypt ;)

**Comment by fniephaus** [comment]
I don't think so. I'd also suggest [letsencrypt](https://letsencrypt.org/) :smiley:

**Comment by bertfreudenberg** [comment]
In the meantime, we're redirecting to http b66d67af8c76b651eb2917a755dcaaabfa9bde1e

**Comment by fniephaus** [comment]
This is not the solution I was hoping for :cry:
We could host Squeak image [here](https://www.hpi.uni-potsdam.de/hirschfeld/artefacts/) if that'd help.
